# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
# relative_permalinks: true

# Setup
title:               doubleCat
tagline:             '..blahblah'
description:         'dev something'
url:                 https://enplus.github.io
baseurl:             /
favicon: public/favicon.ico
navigation: True


paginate:            8

# About/contact
author:
  name:              Enplus
  url:               https://haskell.site
  email:             doublebind96@gmail.com

# Custom vars
version:             1.0.0
plugins: ['jekyll-paginate']

# 
markdown: kramdown
# krandown - Markdown 개조판.

highlighter: rouge

